### ISSUE TITLE
The demo is offline

### ISSUE THREAD

**Issue by frederikhors** [chung-leong/relaks#5]
The demo is offline: https://trambar.io/examples/starwars-v/#/films/1/.

**Comment by chung-leong** [comment]
Thanks for the heads up. The location of the data source changed. The demo should work now.

**Comment by frederikhors** [comment]
Nope it's not:

![image](https://user-images.githubusercontent.com/41120635/93669707-42bde100-fa96-11ea-8dbf-1ceffd7a9b3e.png)

**Comment by chung-leong** [comment]
Try clearing your cache. It should be pulling the data from swapi.dev and not swapi.co.
